services:
  mariadb:
    build:
      context: ../..
      dockerfile: docker/v1/Dockerfile.mariadb
      no_cache: true
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: CRMvizzYgOrl4ljB2uY9MtkLhIIpucKx
    volumes:
      - mariadb_data:/var/lib/mariadb
    ports:
      - "3306:3306"
    networks:
      - app_network
    restart: unless-stopped

  nodejs:
    build:
      context: ../..
      dockerfile: docker/v1/Dockerfile.node
      no_cache: true
    container_name: nodejs_app
    environment:
      DATABASE_URL: mariadb://01KBW95T0KDJR9DXB76N85YN44:01KBW946RN5ZD4MP9R46R7AP57_01kbw94d5wv0cd4521bw1andra@genrobotics:3306/genrobotics
      NODE_ENV: production
      SOCKET_PORT: 11758
    depends_on:
      - mariadb
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    build:
      context: ../..
      dockerfile: docker/v1/Dockerfile.nginx
      no_cache: true
    container_name: nginx_proxy
    ports:
      - "8883:80"
      - "8884:443"
    depends_on:
      - nodejs
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  app_network:
    driver: bridge
